version: '3.8'

services:
  web:
    build: .
    container_name: naija_agent_x_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
